### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by coreyfarrell** [cfware/babel-plugin-template-html-minifier#14]
I'd like to add a LICENSE file, though for this I need feedback or permission from @goto-bus-stop.  package.json already specifies MIT, I won't be changing this.  Since this module is derived from your work I want to make sure I honor your copyright rights.

I'd like to copy https://github.com/cfware/vinyl-rollup/blob/76c826c6e381bb4686664ad759c3e774f4e8b82d/LICENSE into this repository.  I can add a line below `Copyright (c) 2018 CFWare, LLC` for the derived copyright.  If you want this please let me know the exact text you want me to use.

Alternatively if you'd like to 'release all license claim', please comment here saying so.  Either way makes no difference to me.  I do not plan to remove the [attribution](https://github.com/cfware/babel-plugin-template-html-minifier#attribution) from the README.md (of course unless you ask me to).

Additionally I plan to put myself in for the package.json `author` field - this only allows a single name.

Please let me know any thoughts or objections.

**Comment by goto-bus-stop** [comment]
I'm happy to release all license claim. From my perspective, this package is yours now :P 

(I don't know what the exact legalities are, but I also don't plan to sue you for taking over maintenance of a package, so…)

**Comment by coreyfarrell** [comment]
Thanks for responding.  Also thanks again for letting me take this over!
