### ISSUE TITLE
Minify with postcss and terser

### ISSUE THREAD

**Issue by quetzalsly** [cfware/babel-plugin-template-html-minifier#22]
It would be nice to use the newer plugins rather than uglify and clean-css.
I was able to use terser with:

```
const {minify} = require('terser');
minifyJS:           (code) => minify(code).code,
```

But postcss uses async funcs which isn't supported right now by html-minifier it seems.

Is there any possibility this plugin could have some kind of option for this?
I want to use postcss-preset-env and autoprefixer and stuff and run each .js file through those.

I am using polymer shop sample code and they use html and css inside templates inside of .js files so that's how I found this plugin.

**Comment by coreyfarrell** [comment]
Any change to the way `html-minifier` works would have to happen in `html-minifier`.  This module just extracts HTML source from JS templates and forwards to `html-minifier` with the options you specify.  Obviously you can pass the `minifyJS: code -> terser(code).code` option to `html-minifier` with the options to this plugin.  Just be aware `html-minifier` ignores `<script type="module">`.  Overall I advise against putting JavaScript inline in your html templates, instead link events to functions outside the template `onclick=${event => this._handleClick(event)}` (sorry I'm not a lit-html user so I'm not sure of the exact correct syntax for lit).

It looks like some work was attempted to enable async / callback interface with minifyCSS but that appears to have stalled.  Also my understanding is that babel plugins have to be sync so I would be unable to use an async interface even if it existed.

I'm closing this issue as I do not believe anything can be done from this repo, these are upstream limitations.
