### ISSUE TITLE
error when minifying member expression with a mixin

### ISSUE THREAD

**Issue by LarsDenBakker** [cfware/babel-plugin-template-html-minifier#32]
The minifier fails on this construction:

```javascript
import base from 'hyperhtml-element';

const someMixin = baseClass => class extends baseClass {

};

export class ele extends someMixin(base) {
	render() {
		this.html`<div >test</div>`;
		this.nothtml`<div >test</div>`;
	}
}
```

but it handles this just fine:

```javascript
import base from 'hyperhtml-element';

export class ele extends base {
	render() {
		this.html`<div >test</div>`;
		this.nothtml`<div >test</div>`;
	}
}
```

This is because here it ends up in the else clause: https://github.com/cfware/babel-plugin-template-html-minifier/blob/master/lib/index.js#L121 but `superClass.object` is undefined causing the plugin to crash.

I've looking into creating a PR for this, but I don't understand what some parts of the code do. How do you propose this to be tackeld?

**Comment by coreyfarrell** [comment]
Without digging too deep right now I suspect that else statement on line 121 should be `else if (superClass.object)` to squash the crash.  I'm not sure how to actually support minifying this use case other than enabling support for #17.

**Comment by LarsDenBakker** [comment]
What does the code in the else clause do? Does it analyze the super class somehow?

Indeed just adding a guard clause would be fine, you'd lose out on analyzing the mixin but it gets super complex if you have to do that cross-files.

In my case the code it crashes on is not a template tag that I want to minify, so it's fine for me.

**Comment by coreyfarrell** [comment]
The `else` clause is for when the base class is from a named export and imported with star, for example:
```js
import * as base from '@cfware/shadow-element';

class element extends base.ShadowElement {
 // handleStar looks at the star import `base` and finds the `ShadowElement` member.
}
```

It's an obscure use case that I personally don't even use, mostly included for completeness.  I didn't think of mixins when writing this code.
