### ISSUE TITLE
Cannot find module '*/package.json' when using with webpack and resolve aliases

### ISSUE THREAD

**Issue by marcin-serwin** [cfware/babel-plugin-template-html-minifier#4]
Webpack has an [option](https://webpack.js.org/configuration/resolve/) to affect how the resolving is done. For example, one can set alias `Utilities: path.resolve(__dirname, 'src/utilities/')` and then write `import something from "Utilities/something.js"`. The plugin will, however, complain that it cannot find module `Utilities`, which makes this feature unusable with it.

I think simply ignoring case when a module does not exist would solve the issue.

**Comment by coreyfarrell** [comment]
@Toxyxer could you give #5 a try to be sure I haven't missed anything?  Thanks!

**Comment by marcin-serwin** [comment]
@coreyfarrell Works in my case.
