### ISSUE TITLE
CSS compatible divider

### ISSUE THREAD

**Issue by aletorrado** [cfware/babel-plugin-template-html-minifier#7]
Hi, I'm the author of a very similar project named [babel-plugin-polymer-html-minifier](https://github.com/aletorrado/babel-plugin-polymer-html-minifier). I've noticed that you don't use a CSS compatible separator with a syntax such as `prop:value`.

`html-minifier` handles the `style` attribute content specially, discarding any invalid syntax, so I think this example won't work with your project:

```
<div style="
  ${styles}
"></div>
```

**Comment by coreyfarrell** [comment]
This happens when `minifyCSS: true` is used.  I'll be posting an update to deal with that and an issue with unquoted attributes soon.  Thanks for the report.

**Comment by coreyfarrell** [comment]
Fixed by release of v2.1.1.
